name: Deploy Next.js Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add droplet to known_hosts
      run: |
        ssh-keyscan ${{ secrets.DO_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy
      env:
        DO_USER: ${{ secrets.DO_USER }}
        DO_IP: ${{ secrets.DO_IP }}
      run: |
        ssh $DO_USER@$DO_IP << 'EOF'
          cd paste_bin_clone
          git pull origin main
          npm install
          npm run build
          pm2 restart paste-bin-clone || pm2 start npm --name "paste-bin-clone" -- start
        EOF
